services:
  currency-frontend:
    image: ghcr.io/matejma2ur/currency-converter-web:latest
    container_name: currency-fe
    ports:
      - "5001:8080"
    depends_on:
      - currency-api
  
  currency-api:
    image: ghcr.io/matejma2ur/currency-converter-api:latest
    container_name: currency-be
    ports:
      - "5002:8080"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update --interval 30 currency-fe currency-be
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=extremlysecuretoken
    ports:
      - 8080:8080

volumes:
  mariadb:
