services:
  currency-frontend:
    image: ghcr.io/matejma2ur/currency-converter-web:latest
    ports:
      - "5001:8080"
    depends_on:
      - currency-api
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
  
  currency-api:
    image: ghcr.io/matejma2ur/currency-converter-api:latest
    ports:
      - "5002:8080"
    depends_on:
      - db
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --debug --http-api-update
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=extremlysecuretoken
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 8080:8080

volumes:
  mariadb:
